export enum ActionTypes {
  GET_EXCHANGE_RATES_BY_DATE = "GET_EXCHANGE_RATES_BY_DATE",
  GET_EXCHANGE_MOCK = "GET_EXCHANGE_MOCK",
}

export enum MutationTypes {
  SET_CHOSEN_DATA = "SET_CHOSEN_DATA",
  SET_EXCHANGE_RATE = "SET_EXCHANGE_RATE",
}
